name: build-android

on: 
  workflow_dispatch:

env:
  BINARY_PREFIX: "colly-for-netcloud_"
  BINARY_SUFFIX: ""
  PR_PROMPT: "::warning:: Build artifact will not be uploaded due to the workflow is trigged by pull request."
  LD_FLAGS: "-w -s"

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
      - run: |
          go mod init github.com/luoyingying123/Colly-for-Netcloud
          go mod tidy
      - name: Cache downloaded module
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d 
      - name: Build binary file
        env:
          GOOS: android
          GOARCH: arm64
          CC : "$NDKROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
          CXX: "$NDKROOT/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android28-clang++"
        run: |
          go build -o "colly-for-netcloud" -trimpath -ldflags "$LD_FLAGS" .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !github.head_ref }}
        with:
          name: android_arm64
          path: output/
