name: build-android

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - run: |
          go mod init github.com/luoyingying123/Colly-for-Netcloud
          go mod tidy
      - uses: HoshinoSuzumi/setup-ndk@v1.5.4
        with:
          ndk-version: r26d 
      - name: Build binary file
        env:
          GOOS: android
          GOARCH: arm64
          CC : "/opt/hostedtoolcache/ndk/r26d/x64/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
          CXX: "/opt/hostedtoolcache/ndk/r26d/x64/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android28-clang++"
        run: |
          go build -ldflags "-X main.Version=$version -s -w -linkmode=external -extldflags=-pie" -o "colly-for-netcloud-arm64"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !github.head_ref }}
        with:
          name: colly-for-netcloud
          path: colly-for-netcloud-arm64
