name: build-windows

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
      - name: Build binary file
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 1
          CC : x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++
        run: |
          go mod tidy
          go build -ldflags "-linkmode=external -extldflags=-static" -o "NECspider-go_amd64.exe"
          ls -a
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_amd64
          path: NECspider-go_amd64.exe
