name: build-windows

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build binary CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Build binary file
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go mod tidy
          go build -ldflags "-s -w" -o "NECspider-go_amd64.exe"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_amd64
          path: NECspider-go_amd64.exe
