name: fm

on: 
  workflow_dispatch:
  
jobs:
  build:
    name: collying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          go fmt main.go
      - uses: actions/upload-artifact@v4
        with:
          name: src
          path: main.go
