# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: run-test

on:
  workflow_dispatch:
    inputs:
      parallelism:
        required: false
        type: string
        default: "500"
      begin_id:
        required: true
        type: string
      end_id:
        required: true
        type: string

jobs:
  collying:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Go run
      run: |
        go mod tidy
        go run main.go -p ${{inputs.parallelism}} -- ${{inputs.begin_id}} ${{inputs.end_id}} &
        sleep 30s
        curl -o goroutine-dalta http://localhost:6060/debug/pprof/goroutine?seconds=30
        curl -o block-dalta http://localhost:6060/debug/pprof/block?seconds=30
        go install github.com/google/pprof@latest
        pprof -traces block-delta > block.txt
        pprof -traces goroutine-delta > goroutine.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test
        path: block.txt, goroutine.txt