name: run

on: 
  workflow_dispatch:
  
jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
      - run: |
          ./colly-for-netcloud_amd64 100 200 -p 50