name: run

on: 
  workflow_dispatch:
  
jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x colly-for-netcloud_amd64
          ./colly-for-netcloud_amd64 100 200 -p 50
