name: run

on: 
  workflow_dispatch:
  
jobs:
  build:
    name: collying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x colly-for-netcloud_amd64
          ./colly-for-netcloud_amd64 -p 1000 -- -1 100000
